version: '3.5'

services:
  db:
    build: .
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
      - ./volumes/data:/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    environment:
      - LANG=
      - POSTGRES_PASSWORD=123456

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 8097:80
