version: '3.5'

services:
  db:
    build: ./docker
    restart: always
    shm_size: 1G
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
      - ./volumes/data:/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    environment:
      - LANG=
      - POSTGRES_PASSWORD=msdfhfg45643324sdsdasqq2ghxp1ab7

  app:
    image: fffaraz/php
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - default
      - isolated_nw
    ports:
      - 8081:80

  adminer: # https://github.com/vrana/adminer
      image: adminer # https://github.com/TimWolla/docker-adminer
      restart: always
      depends_on:
        - db
      logging:
        driver: "none"
      networks:
        - default
        - isolated_nw
      ports:
        - 8082:8080
